// http://doc.qt.io/qt-5/qtqml-cppintegration-data.html

// http://doc.qt.io/qt-5/qmetatype.html
var Void                  =   43; // QMetaType::Void                  void
var Bool                  =    1; // QMetaType::Bool                  bool
var Int                   =    2; // QMetaType::Int                   int
var UInt                  =    3; // QMetaType::UInt                  unsigned int
var Double                =    6; // QMetaType::Double                double
var QChar                 =    7; // QMetaType::QChar                 QChar
var QString               =   10; // QMetaType::QString               QString
var QByteArray            =   12; // QMetaType::QByteArray            QByteArray
var Nullptr               =   51; // QMetaType::Nullptr               std::nullptr_t
var VoidStar              =   31; // QMetaType::VoidStar              void *
var Long                  =   32; // QMetaType::Long                  long
var LongLong              =    4; // QMetaType::LongLong              LongLong
var Short                 =   33; // QMetaType::Short                 short
var Char                  =   34; // QMetaType::Char                  char
var ULong                 =   35; // QMetaType::ULong                 unsigned long
var ULongLong             =    5; // QMetaType::ULongLong             ULongLong
var UShort                =   36; // QMetaType::UShort                unsigned short
var SChar                 =   40; // QMetaType::SChar                 signed char
var UChar                 =   37; // QMetaType::UChar                 unsigned char
var Float                 =   38; // QMetaType::Float                 float
var QObjectStar           =   39; // QMetaType::QObjectStar           QObject *
var QVariant              =   41; // QMetaType::QVariant              QVariant
var QCursor               =   74; // QMetaType::QCursor               QCursor
var QDate                 =   14; // QMetaType::QDate                 QDate
var QSize                 =   21; // QMetaType::QSize                 QSize
var QTime                 =   15; // QMetaType::QTime                 QTime
var QVariantList          =    9; // QMetaType::QVariantList          QVariantList
var QPolygon              =   71; // QMetaType::QPolygon              QPolygon
var QPolygonF             =   86; // QMetaType::QPolygonF             QPolygonF
var QColor                =   67; // QMetaType::QColor                QColor
var QSizeF                =   22; // QMetaType::QSizeF                QSizeF
var QRectF                =   20; // QMetaType::QRectF                QRectF
var QLine                 =   23; // QMetaType::QLine                 QLine
var QTextLength           =   77; // QMetaType::QTextLength           QTextLength
var QStringList           =   11; // QMetaType::QStringList           QStringList
var QVariantMap           =    8; // QMetaType::QVariantMap           QVariantMap
var QVariantHash          =   28; // QMetaType::QVariantHash          QVariantHash
var QIcon                 =   69; // QMetaType::QIcon                 QIcon
var QPen                  =   76; // QMetaType::QPen                  QPen
var QLineF                =   24; // QMetaType::QLineF                QLineF
var QTextFormat           =   78; // QMetaType::QTextFormat           QTextFormat
var QRect                 =   19; // QMetaType::QRect                 QRect
var QPoint                =   25; // QMetaType::QPoint                QPoint
var QUrl                  =   17; // QMetaType::QUrl                  QUrl
var QRegExp               =   27; // QMetaType::QRegExp               QRegExp
var QRegularExpression    =   44; // QMetaType::QRegularExpression    QRegularExpression
var QDateTime             =   16; // QMetaType::QDateTime             QDateTime
var QPointF               =   26; // QMetaType::QPointF               QPointF
var QPalette              =   68; // QMetaType::QPalette              QPalette
var QFont                 =   64; // QMetaType::QFont                 QFont
var QBrush                =   66; // QMetaType::QBrush                QBrush
var QRegion               =   72; // QMetaType::QRegion               QRegion
var QBitArray             =   13; // QMetaType::QBitArray             QBitArray
var QImage                =   70; // QMetaType::QImage                QImage
var QKeySequence          =   75; // QMetaType::QKeySequence          QKeySequence
var QSizePolicy           =  121; // QMetaType::QSizePolicy           QSizePolicy
var QPixmap               =   65; // QMetaType::QPixmap               QPixmap
var QLocale               =   18; // QMetaType::QLocale               QLocale
var QBitmap               =   73; // QMetaType::QBitmap               QBitmap
var QMatrix               =   79; // QMetaType::QMatrix               QMatrix
var QTransform            =   80; // QMetaType::QTransform            QTransform
var QMatrix4x4            =   81; // QMetaType::QMatrix4x4            QMatrix4x4
var QVector2D             =   82; // QMetaType::QVector2D             QVector2D
var QVector3D             =   83; // QMetaType::QVector3D             QVector3D
var QVector4D             =   84; // QMetaType::QVector4D             QVector4D
var QQuaternion           =   85; // QMetaType::QQuaternion           QQuaternion
var QEasingCurve          =   29; // QMetaType::QEasingCurve          QEasingCurve
var QJsonValue            =   45; // QMetaType::QJsonValue            QJsonValue
var QJsonObject           =   46; // QMetaType::QJsonObject           QJsonObject
var QJsonArray            =   47; // QMetaType::QJsonArray            QJsonArray
var QJsonDocument         =   48; // QMetaType::QJsonDocument         QJsonDocument
var QModelIndex           =   42; // QMetaType::QModelIndex           QModelIndex
var QPersistentModelIndex =   50; // QMetaType::QPersistentModelIndex QPersistentModelIndex (since 5.5)
var QUuid                 =   30; // QMetaType::QUuid                 QUuid
var QByteArrayList        =   49; // QMetaType::QByteArrayList        QByteArrayList
var User                  = 1024; // QMetaType::User                  Base value for user types
var UnknownType           =    0; // QMetaType::UnknownType           This is an invalid type id. It is returned from QMetaType for types that are not registered
